hydra:
  run:
    dir: ./run
  sweep:
    # Output directory for sweep runs
    dir: ./run/mirgahney/${now:%Y-%m-%d_%H-%M-%S}
    # Output sub directory for sweep runs.
    subdir: ${hydra.job.num}_${hydra.job.id}
