seed: 2
tensorType: torch.cuda.FloatTensor
device: cuda
gpu_name: cuda

optimizer:
  lr: 1e-3
  weight_decay: 2e-3

train:
  sghmc_step: 1
  iterations: 2500
  load: False
  rep: 1
  train_hyper: 100

model:
  kernel: 'rbf'
  expansion_factor: 0
  M: 384

dir: '/home/mirgahney/Projects/Personal' #/DeepResCGP_SGHMC'
top_dir: ${dir}/DeepResCGP_SGHMC/test #run

data:
  name: 'fashion_mnist' #'fashion_mnist' #'cifar'
  path: ${dir}/datasets
  batch_size: 128
  num_classes: 10
  train_pct: 0.8333333333

save_model: False

defaults:
  - models: plain_cgp_net8
  #- cost:  #image_velocity_tracking #image_trajectory_tracking
  - hydra/run: customized
